### ISSUE TITLE
Dynamic Stats choke when unicode is used for layer names or node names

### ISSUE THREAD

**Issue by mrJeppard** [ucscHexmap/hexagram#44]
Dynamic stats was not working on the first version of the MusicMap. The error points to the use of unicode in layer names:

Sorry, Returned with code: 1 Traceback (most recent call last): File "/data/www/server/pythonCall.py", line 124, in <module> , return_code = pythonWrapper(sys.argv[1], sys.argv[2], sys.argv[3]) File "/data/www/server/pythonCall.py", line 94, in pythonWrapper result = module.fromNodejs(opts) File "/hive/groups/hexmap/prod/compute/calc/statsDynamic.py", line 106, in fromNodejs , return dynamicStats(args) File "/hive/groups/hexmap/prod/compute/calc/statsDynamic.py", line 86, in dynamicStats filename = layerFiles[layerName] KeyError: u'Tag: espa\xf1ol'

**Comment by ucscHexmap** [comment]
We don't handle unicode anywhere in the app. We should only allow the printable characters in the ASCII set for node and layer names.

**Comment by terraswat** [comment]
Another trace for dynamic layout stats with attr: '1/0' of the unitTest map:

error: Returned with code: 1
Traceback (most recent call last):
  File "/cluster/home/swat/dev/www/programs/server/assets/app/pythonCall.py", line 124, in <module>
,    return_code = pythonWrapper(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/cluster/home/swat/dev/www/programs/server/assets/app/pythonCall.py", line 94, in pythonWrapper
    result = module.fromNodejs(opts)
  File "/hive/groups/hexmap/dev/compute/calc/statsDynamic.py", line 106, in fromNodejs
,    return dynamicStats(args)
  File "/hive/groups/hexmap/dev/compute/calc/statsDynamic.py", line 59, in dynamicStats
    resultFile = leesL.dynamicCallLeesL(parm)
  File "/hive/groups/hexmap/dev/compute/calc/leesL.py", line 468, in dynamicCallLeesL
,    dynamicAttr = attrPreProcessing4Lee(pd.Series(parm['dynamicData'][parm['layerA']]),xys)
KeyError: u'1/0'
